[package]
name = "input-leap-rs"
version = "2.4.0"
edition = "2021"

[lib]
name = "input_leap_rs"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
anyhow = "1.0"

[build-dependencies]
cxx-build = "1.0"
